# DEFAULT VM CONFIG
nbofvms: 1
vm_user: ubuntu
image: trusty64
flavor: m1.sp
os_security_groups: "{{ plat }}-secgrp"
fip: admin_floating_net
availability_zone: nova
region_name: RegionOne
key_name: son-install
int_net_id: "2fef1357-46f2-4464-a6f2-2bd2a4d57120" # QUAL
ext_net_id: "83d48c16-8461-4939-9cb3-e7e240ec9538" # FIP

