# DEFAULT VM CONFIG
vm_user: ubuntu
nbofvms: 1
image: u14-cldimg
flavor: m1.small
os_security_groups: "{{ plat }}-secgrp"
fip: "53d43a3e-8c86-48e6-b1cb-f1f2c48833de" # PROVIDER
availability_zone: nova
region_name: RegionOne
key_name: son-install

# DEMO-Netw
#int_net_id: "e25c4920-65b4-4308-a405-e64ad2770cc2" # son-demo.mgmt-netw (172.22.1.0/24)
int_net_id: "ea7d9c50-5b1e-4968-804d-a6ec11c318c5" # sonata.dem-subnet (192.168.10.0/24)
#net1_net_id: "fb899ce6-853f-4ec7-8bbf-2f6da0d843d3" # son-demo.cpin-netw (192.168.60.0/24)
#net2_net_id: "579bc3fc-c3ed-4495-b459-9c5f74e71320" # son-demo.cpou-netw (192.168.70.0/24)
ext_net_id: "53d43a3e-8c86-48e6-b1cb-f1f2c48833de" # provider.dem-net (10.100.32.0/24)

