---
# tasks file for PostgreSQL
- include_tasks: centos6.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"

- include_tasks: centos7.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"


- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

