- name: check if MGMT network exists
  #shell: "docker network inspect -f '{{ .Name }}' vcdn-mgmt"
  shell: "docker network inspect vcdn-mgmt"
  ignore_errors: yes
  register: mgmt_net_status

- name: "Docker User Defined Network (vCDN MGMT)"
  shell: "docker network create --driver=bridge \
    --subnet=172.22.100.0/24 --gateway=172.22.100.1 \
    --ip-range=172.22.100.128/25 '{{ vl_mgmt }}'"

