---
# tasks file for odoo

- name: installing ODOO on Redhat distros
  include_tasks: "{{ ansible_distribution_release }}.yml"
  when: ansible_os_family == "RedHat"

- name: installing ODOO on Debian distros
  include_tasks: debian.yml
  when: ansible_os_family == "Debian"

# Managing firewall
- name: start 'firewalld' service
  service: name=firewalld state=started

- name: open Odoo listening port at fw
  firewalld: port=8069/tcp permanent=true state=enabled
  notify: reload firewalld

