---

- name: SONATA CMUD v3.1
  hosts: localhost
  become: false
  connection: local
  vars:
    distro: '{{ ansible_distribution_release }}'
  pre_tasks:
    - debug: msg="##### START-DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"
    - file:
        path: "{{ lookup('env','HOME') }}/ansible.log"
        state: touch
        owner: "{{ lookup('env','USER') }}"
        group: "{{ lookup('env','USER') }}"
        mode: "u=rw,g=rw,o=rw"
    - file:
        path: "{{ lookup('env','PWD') }}/group_vars/{{ plat }}/hosts"
        state: absent
      when: ops == "create"

# STEP 1 - PREPARE THE LOCAL MACHINE, aka Ansible Control Center (or jump host)
  roles:
    - { role: ntp, become: true }
    - { role: common, become: true }
    - { role: openstackclients, become: true }

# STEP 2 - DEPLOY A NEW INSTANCE
    - { role: vm, when: ops == "create" }

# STEP 3 - DO PACKAGE UPGRADE & TOOLS INSTALLATION TO THE REMOTE MACHINE
- import_playbook: "{{ lookup('env','PWD') }}/utils/deploy/common.yml"

# STEP 4 - DEPLOY SPECIFIC SOFTWARE
- import_playbook: "{{ lookup('env','PWD') }}/{{ ops }}/{{ plat }}/main.yml"
  when: plat != 'vm'

#  post_tasks:
#    - debug: msg="##### END-DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"

