# CENTOS 7
- name: installing EPEL
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/

- name: installing JDK
  #yum: name=java-1.8.0-openjdk state=present update_cache=yes
  yum: name=java-1.7.0-openjdk state=present update_cache=yes

- name: set environment variables
  shell: "export JAVA_HOME=/usr/lib/jvm/jre-1.7.0-openjdk/"
- shell: "export PATH=/usr/lib/jvm/jre-1.7.0-openjdk/bin:{{ ansible_env }}.PATH"

