---
# tasks file for docker-squid

- include_vars: "{{ lookup('env','PWD') }}/roles/docker-squid/defaults/main.yml"
- include_tasks: "{{ lookup('env','PWD') }}/roles/docker-squid/tasks/networks.yml"

- name: get Squid Docker image
  docker_image:
    #name: sameersbn/squid
    name: arocha/vpsa-squid-3.3.8 

- name: start Squid-proxy container
  docker_container:
    name: squid
    #image: sameersbn/squid
    image: arocha/vpsa-squid-3.3.8
    #env:
    state: started
    network_mode: bridge
    networks:

      - name: "{{ vl_mgmt }}"
        aliases:
          - vpsa-mgmt
      - name: "{{ vl_prxin }}"
        aliases:
          - vpsa-prxin
      - name: "{{ vl_prxout }}"
        aliases:
          - vpsa-prxout

    restart_policy: "unless-stopped"
    published_ports:
     - 3128:3128
     - 3129:3129
    volumes:
      - /var/log/sonata/squid:/var/log/squid
    log_driver: syslog # gelf

    #log_options:
    #  syslog-address: tcp://my-syslog-server:514
    #  syslog-facility: daemon

- wait_for: host=0.0.0.0 port=3128 timeout=30 delay=10 state=started

