---
# defaults file for sp

nbofvms: 1
pop: alabs
proj: demo
distro: xenial

# Docker network segment
docker_network_name: son-sp

# SONATA 5G NFV SP development/latest version
sp_ver: dev
domain_name: sonata-nfv.eu
fqdn: "{{ plat }}.{{ pop }}.{{ domain_name }}"

sp_user: sonata
sp_pass: "$1$SRc2ws2Z$rSdCC/UKiatagNdfsTVuf0"

