---

- name: run the SP Keycloak service
  docker_container:
    name: "son-keycloak"
    image: "sonatanfv/son-keycloak:{{ sp_ver }}"
    env:
      #KEYCLOAK_USER: admin 
      #KEYCLOAK_PASSWORD: admin
      KEYCLOAK_USER: "{{ gtk_keycloak_user }}" 
      KEYCLOAK_PASSWORD: "{{ gtk_keycloak_pass }}"
    state: started
    network_mode: bridge
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - son-keycloak
    published_ports:
      - "5601:5601"
    restart_policy: "unless-stopped"
