---
- debug: msg="##### SP GTK DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
# Running the Sonata GK Docker Images

- include_tasks: gtk/val.yml
- include_tasks: gtk/pkg.yml
- include_tasks: gtk/srv.yml
- include_tasks: gtk/fnct.yml
- include_tasks: gtk/rec.yml
- include_tasks: gtk/vim.yml
- include_tasks: gtk/lic.yml
- include_tasks: gtk/kpi.yml
- include_tasks: gtk/usr.yml
- include_tasks: gtk/rlt.yml
- include_tasks: gtk/api.yml

