---
- debug: msg="##### SP MANO DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

# Running the Sonata MANO Docker Images

- include_tasks: mano/pluginmgr.yml
- include_tasks: mano/slm.yml
- include_tasks: mano/flm.yml
- include_tasks: mano/smr.yml
- include_tasks: mano/placement.yml
- include_tasks: mano/placementplg.yml
