---
# tasks file for docker-openvpn

- include_vars: "{{ lookup('env','PWD') }}/roles/docker-openvpn/defaults/main.yml"
- include_tasks: "{{ lookup('env','PWD') }}/roles/docker-openvpn/tasks/networks.yml"

- name: get OpenVPN Docker image
  docker_image:
    #name: kylemanna/openvpn
    name: lconceicao/vpnserver

- name: start OpenVPN Server as a Docker container
  docker_container:
    name: vpnserver
    image: kylemanna/openvpn
    #image: lconceicao/vpnserver
    #env:
    state: started
    network_mode: bridge
    networks:

      - name: "{{ vl_mgmt }}"
        aliases:
          - vpsa-mgmt
      - name: "{{ vl_vpnin }}"
        aliases:
          - vpsa-vpnin
      - name: "{{ vl_vpnout }}"
        aliases:
          - vpsa-vpnout

    restart_policy: "unless-stopped"
    volumes:
      - /var/log/sonata/openvpn:/var/log/openvpn
    log_driver: syslog # gelf

    #log_options:
    #  syslog-address: tcp://my-syslog-server:514
    #  syslog-facility: daemon

