---
# tasks file for roles/docker-vtc

- include_vars: "{{ lookup('env','PWD') }}/roles/docker-vtc/defaults/main.yml"
- include_tasks: "{{ lookup('env','PWD') }}/roles/docker-vtc/tasks/networks.yml"

- name: start vTU as a Docker container
  docker_container:
    name: vtc
    image: sonatanfv/vcdn-vtc-fsm-css
    #env:
    state: started
    network_mode: bridge
    networks:

      - name: "{{ vl_mgmt }}"
        aliases:
          - son-vpsa-mgmt

      - name: "{{ vl_vtcin }}"
        aliases:
          - son-vpsa-vtcin

      - name: "{{ vl_vtcout }}"
        aliases:
          - son-vpsa-vtcout

    restart_policy: "unless-stopped"
    #published_ports: 80:80
    volumes:
      - /var/log/sonata/docker-vtc:/var/log/docker-vtc
    log_driver: syslog # gelf

    #log_options:
    #  syslog-address: tcp://my-syslog-server:514
    #  syslog-facility: daemon

