- debug: msg="##### DEPLOYING DOCKER {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"
- name: install Docker
  include_role:
    name: docker

- debug: msg="##### DEPLOYING UFW {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"
- name: instanciate dockerized UFW
  include_role:
    name: docker-ufw

- debug: msg="##### DEPLOYING NGINX {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"
- name: instanciate dockerized NGINX
  include_role:
    name: docker-nginx

- debug: msg="##### DEPLOYING SQUID {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"
- name: instanciate dockerized SQUID
  include_role:
    name: docker-squid

- debug: msg="##### DEPLOYING SNORT {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"
- name: instanciate dockerized SNORT
  include_role:
    name: docker-snort

- debug: msg="##### DEPLOYING OPENVPN {{ lookup('pipe', 'date +%Y%m%d-%H:%M:%S') }}"
- name: instanciate dockerized OPENVPN
  include_role:
    name: docker-openvpn

