---
- name: "deploy JENKINS CI server to the target VM appliance"
  #hosts: "{{ target | default(localhost) }}"
  hosts: nfvi
  become: true
  connection: ssh
  roles:
  - ntp
  - common
  - jdk
  - firewall
  - nginx
  - jenkins
