
- name: create a new security group for NGINX connections
  os_security_group:
    cloud: "os_{{ pop }}_{{ proj }}"
    state: present
    name: "{{ plat }}-secgrp"
    description: open ports for NGINX connections

- name: create a security rule on that group to allow HTTP connections
  os_security_group_rule:
    cloud: "os_{{ pop }}_{{ proj }}"
    security_group: "{{ plat }}-secgrp"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

- name: create a security rule on that group to allow HTTPS connections
  os_security_group_rule:
    cloud: "os_{{ pop }}_{{ proj }}"
    security_group: "{{ plat }}-secgrp"
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0

