  - name: MONIT MANAGER - running Docker containers
    docker_container:
      name: son-monitor-manager
      image: "sonatanfv/son-monitor-manager:{{ sp_ver }}"
      state: started
      network_mode: bridge
      networks:
        - name: "{{ docker_network_name }}"
          aliases:
            - son-monitor-manager
      published_ports:
        - "8000:8000"
        - "8888:8888"
