
# tasks file for docker

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_release }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

#- include_vars: "{{ lookup('env','PWD') }}/roles/{{ plat }}/defaults/main.yml"

- name: create Docker group
  group:
    name: docker
    state: present

- set_fact:
    vm_user: "{{ lookup('env','USER') }}"    
    when: target == 'localhost'

- name: add Docker group to default user
  user:
    name: "{{ vm_user }}"
    shell: /bin/bash
    groups: docker
    append: yes

- name: create a directory for Docker logging
  file:
    path: /var/log/docker
    state: directory
    owner: '{{ vm_user }}'
    group: docker
    mode: 0775
  become: true

- include_tasks: "{{ ansible_distribution_release }}.yml"

- name: restart docker on Systemd (Ubuntu 16 and CentOS 7)
  systemd: name=docker state=reloaded daemon_reload=yes

