---
# tasks file for docker-snort

- include_vars: "{{ lookup('env','PWD') }}/roles/docker-snort/defaults/main.yml"
- include_tasks: "{{ lookup('env','PWD') }}/roles/docker-snort/tasks/networks.yml"

- name: get Snort Docker image
  docker_image:
    name: glanf/snort

- name: start Snort IDS container
  docker_container:
    name: snort
    image: glanf/snort
    #env:
    state: started
    network_mode: bridge
    networks:

      - name: "{{ vl_mgmt }}"
        aliases:
          - vpsa-mgmt
      - name: "{{ vl_idsin }}"
        aliases:
          - vpsa-idsin
      - name: "{{ vl_idsout }}"
        aliases:
          - vpsa-idsout

    restart_policy: "unless-stopped"
    published_ports:
     - 0:1024
     - 1024:65535
    volumes:
      - /var/log/sonata/snort:/var/log/snort
    log_driver: syslog # gelf

    #log_options:
    #  syslog-address: tcp://my-syslog-server:514
    #  syslog-facility: daemon

#- wait_for: host=0.0.0.0 port=80 timeout=30 delay=10 state=started

